-- Basic Analysis
USE website_traffic_analysis;

SELECT 
    *
FROM
    websitetraffic;

-- Total Visits per Country
SELECT 
    country, COUNT(*) AS visits_per_country
FROM
    websitetraffic
GROUP BY country
ORDER BY visits_per_country DESC; 

-- Browser Usage Statistics
SELECT 
    browser, COUNT(*) AS top_browsers
FROM
    websitetraffic
GROUP BY browser
ORDER BY top_browsers DESC;

-- Average Session Duration per Device Type
SELECT 
    devicetype,
    CEIL(AVG(sessionduration)) AS avg_sessionduration
FROM
    websitetraffic
GROUP BY devicetype;

-- Conversion Rate per Campaign Source
SELECT 
    campaignSource, AVG(conversion)
FROM
    websitetraffic
GROUP BY campaignSource;

-- Revenue Generated by Each Browser
SELECT 
    browser, ROUND(SUM(revenue), 2) AS totalrevenue
FROM
    websitetraffic
GROUP BY browser
ORDER BY totalrevenue DESC;

-- Analysis of User Behavior Across Multiple Sessions
SELECT 
    userid,
    COUNT(DISTINCT sessionid) AS sessioncount,
    round(SUM(revenue)) AS totalrevenue
FROM
    websitetraffic
GROUP BY userid
HAVING sessioncount > 1
ORDER BY totalrevenue DESC;

-- Day of Week Analysis
SELECT 
    DAYOFWEEK(Timestamp) AS dayofweek,
    COUNT(*) AS visitcount,
    AVG(sessionduration) AS avgsessionduration
FROM
    websitetraffic
GROUP BY DAYOFWEEK(Timestamp)
ORDER BY visitcount DESC;

-- Sessions with High Engagement (Multiple Page Views and Conversions)
SELECT 
    userid, sessionid, pageviews, conversion
FROM
    websitetraffic
WHERE
    pageviews > 10 AND conversion = 1
ORDER BY pageviews DESC;

-- Revenue and Clicks by Campaign Source
SELECT 
    campaignsource,
    round(SUM(revenue)) AS totalrevenue,
    SUM(adclicks) AS totaladclicks
FROM
    websitetraffic
GROUP BY campaignsource
ORDER BY totalrevenue DESC;

-- New vs. Returning Visitors
SELECT 
    CASE
        WHEN
            userid IN (SELECT 
                    userid
                FROM
                    websitetraffic
                GROUP BY userid
                HAVING COUNT(DISTINCT sessionid) > 1)
        THEN
            'Returning'
        ELSE 'New'
    END AS visitortype,
    COUNT(*) AS visitcount
FROM
    websitetraffic
GROUP BY visitortype;


